import {
  Globe2,
  SearchCheck,
  Undo2,
  ScanSearch,
  Link2,
  Server,
  Mail,
  ShieldCheck,
  Shield,
  HeartPulse,
  FilePlus2,
  KeyRound,
  Fingerprint,
  MailCheck,
  Activity,
  Wifi,
  LocateFixed,
  Route,
  MapPin,
  MailSearch,
  ShieldBan,
  Binary,
  ArrowLeftRight,
  ContactRound,
  Network,
  PlusCircle,
  Braces,
  Minimize2,
  Maximize2,
  Calculator,
  CheckCheck,
  Building2,
  ArrowRightLeft,
  PanelTop,
  MonitorCog,
  FileKey2,
  ExternalLink,
  Send,
  CornerDownRight,
  GitBranch,
  Unlink,
  Image,
  Database,
  FileJson2,
  UserRoundCheck,
  ListTree,
  Monitor,
  ChartNoAxesCombined,
  Languages,
  TextSearch,
  Bot,
  Plug,
  Microchip,
  Shuffle,
  Waypoints,
} from "lucide-react";
export const toolIcons: Record<string, typeof Globe2> = {
  "dns-checker": Globe2,
  "dns-validation": SearchCheck,
  "reverse-ip": Undo2,
  "dns-lookup": ScanSearch,
  cname: Link2,
  ns: Server,
  mx: Mail,
  spf: ShieldCheck,
  dmarc: Shield,
  health: HeartPulse,
  "dmarc-generator": FilePlus2,
  dnskey: KeyRound,
  ds: Fingerprint,
  dkim: MailCheck,
  "ping-ipv4": Activity,
  "ping-ipv6": Wifi,
  "my-ip": LocateFixed,
  traceroute: Route,
  "ip-location": MapPin,
  "email-header": MailSearch,
  blacklist: ShieldBan,
  "ip-decimal": Binary,
  "ip-hostname": ArrowLeftRight,
  "ip-whois": ContactRound,
  "ipv6-whois": Network,
  "ipv4-ipv6": ArrowRightLeft,
  "ipv6-generate": PlusCircle,
  "cidr-range": Maximize2,
  "range-cidr": Minimize2,
  "ipv6-compress": Minimize2,
  "ipv6-expand": Maximize2,
  subnet: Calculator,
  "ipv6-ipv4": ArrowLeftRight,
  "ipv6-check": CheckCheck,
  "my-isp": Building2,
  "domain-ip": Waypoints,
  headers: PanelTop,
  "server-os": MonitorCog,
  "md5-base64": FileKey2,
  "url-opener": ExternalLink,
  smtp: Send,
  htaccess: CornerDownRight,
  rewrite: GitBranch,
  "broken-links": Unlink,
  "open-graph": Image,
  raid: Database,
  "binary-text": Binary,
  "text-binary": Braces,
  json: FileJson2,
  "email-verify": UserRoundCheck,
  "link-analyzer": ListTree,
  "user-agent": Monitor,
  pagerank: ChartNoAxesCombined,
  punycode: Languages,
  serp: TextSearch,
  robots: Bot,
  port: Plug,
  "mac-lookup": Microchip,
  "mac-generator": Shuffle,
  asn: Network,
};
